# Application Name
spring.application.name=InsuranceManagementSystem

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/insurance
spring.datasource.username=root
spring.datasource.password=AmitMono@897879
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html