# Application Name
spring.application.name=InsuranceManagementSystem
spring.profiles.active=local

app.cors.allowed-origin=http://localhost:5173

# Cookie Configuration
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.secure=true
#server.servlet.session.cookie.same-site=strict
#server.servlet.session.cookie.path=/
